# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "amazon_regions", :force => true do |t|
    t.column "short_name",      :string, :default => "", :null => false
    t.column "full_name",       :string, :default => "", :null => false
    t.column "currency_symbol", :string, :default => "", :null => false
    t.column "domain",          :string, :default => "", :null => false
    t.column "image",           :string, :default => "", :null => false
    t.column "shipping_rates",  :string, :default => "", :null => false
    t.column "associate_id",    :string
  end

  create_table "cache_sellers", :id => false, :force => true do |t|
    t.column "seller_id",  :string, :limit => 50
    t.column "nickname",   :string, :limit => 50
    t.column "glancepage", :string, :limit => 50
  end

  create_table "feeds", :force => true do |t|
    t.column "asin",                  :string
    t.column "amazon_region_id",      :integer
    t.column "max_price",             :integer,  :limit => 10, :precision => 10, :scale => 0
    t.column "min_price",             :integer,  :limit => 10, :precision => 10, :scale => 0
    t.column "condition_new",         :integer
    t.column "condition_used",        :integer
    t.column "condition_collectable", :integer
    t.column "min_feedback_count",    :integer
    t.column "min_star_rating",       :integer,  :limit => 10, :precision => 10, :scale => 0
    t.column "date_created",          :datetime
    t.column "text_include",          :string
    t.column "text_exclude",          :string
    t.column "include_international", :integer
    t.column "include_new_sellers",   :integer
  end

  add_index "feeds", ["amazon_region_id"], :name => "fk_feed_amazon_region"

end
